### ISSUE TITLE
Improve short description

### ISSUE THREAD

**Issue by cgosorio** [mjuez/early-im-fault-diagnosis#1]
Right now, the way is written "A multilabel PCA + decision-tree model..." wrongly suggests that a multilabel PCA is being used. I thinks it would better "A PCA + multilabel decision-tree model..." or even better "A model for early detection of multiple faults in induction motors based on the use of PCA and multilabel decision-trees"

**Comment by mjuez** [comment]
You are right, I've changed the description to your proposal.
Thanks.
