### ISSUE TITLE
DATA Available or not

### ISSUE THREAD

**Issue by AuroraPlus0** [mjuez/early-im-fault-diagnosis#2]
Hi Could you pls help to share the raw data, good program , thanks

**Comment by mjuez** [comment]
Hi, unfortunately the data is not publicly available. Is a proprietary dataset from [HSP Digital research group](http://www.hspdigital.org/content/view/12/26/lang,es/). You can contact them using the following [contact form](http://www.hspdigital.org/component/option,com_contact/Itemid,3/lang,es/).
